# Generated by Django 5.2.4 on 2025-07-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleBoxHousingBoreDia', models.CharField(max_length=100)),
                ('bearingSeatDiameter', models.CharField(max_length=100)),
                ('condemningDia', models.CharField(max_length=100)),
                ('intermediateWWP', models.CharField(max_length=100)),
                ('lastShopIssueSize', models.CharField(max_length=100)),
                ('rollerBearingBoreDia', models.CharField(max_length=100)),
                ('rollerBearingOuterDia', models.CharField(max_length=100)),
                ('rollerBearingWidth', models.CharField(max_length=100)),
                ('treadDiameterNew', models.CharField(max_length=100)),
                ('variationSameAxle', models.CharField(max_length=100)),
                ('variationSameBogie', models.CharField(max_length=100)),
                ('variationSameCoach', models.CharField(max_length=100)),
                ('wheelDiscWidth', models.CharField(max_length=100)),
                ('wheelGauge', models.CharField(max_length=100)),
                ('wheelProfile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wheels.wheelfields')),
            ],
        ),
    ]
